version: '3'

services:

  locust-master:
    build:
      context: ..
      dockerfile: dockerfiles/master/Dockerfile
    restart: always
    ports:
      - 8089:8089
    networks:
      locust-swarm:
        aliases:
          - master

  locust-slave-1:
    build:
      context: ..
      dockerfile: dockerfiles/slave/Dockerfile
    restart: always
    environment:
      - MASTER_HOST=locust-master
    networks:
      - locust-swarm
    depends_on:
      - locust-master

  locust-slave-2:
    build:
      context: ..
      dockerfile: dockerfiles/slave/Dockerfile
    restart: always
    environment:
      - MASTER_HOST=locust-master
    networks:
      - locust-swarm
    depends_on:
      - locust-master

  locust-slave-3:
    build:
      context: ..
      dockerfile: dockerfiles/slave/Dockerfile
    restart: always
    environment:
      - MASTER_HOST=locust-master
    networks:
      - locust-swarm
    depends_on:
      - locust-master

networks:
  locust-swarm: